# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: npm i -g appcenter-cli
  displayName: Install appcenter CLI tool

- script: |
    appcenter test run uitest --app "v-andrem-microsoft.com/vsts-id-variable-test" --devices 766d134b --app-path D:/a/1/s/aWest3Dint28142.apk --test-series "master" --locale "en_US" --build-dir D:/a/1/s/Debug --vsts-id-variable TEST_RUN_ID --token a4a8419a64cf7cf5c5f0f6e72b3477830ca0bf94
  displayName: 'Run App Center tests'

- script: set T
  displayName: Print environment variables