# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- script: |
    echo on
    echo "##vso[task.setvariable variable=TEST_RUN_ID]947b95de-2cc3-40d1-b27b-fc2002dbdb3f"
  displayName: 'Run App Center tests'

- script: set T
  displayName: Print environment variables